repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: fix-encoding-pragma
      - id: destroyed-symlinks
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: sort-simple-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
