- name: Install Portainer
  hosts: networking
  become: yes
  serial: 1
  tasks:
    - import_tasks: networking-setup.yaml

    # ####################################
    # Run container
    # ####################################
    - name: Start/Update Portainer container
      docker_container:
        name: portainer
        image: portainer/portainer-ce:2.21.2
        pull: yes
        restart_policy: unless-stopped
        env:
          TZ: "{{ timezone }}"
        labels:
          traefik.docker.network:
          traefik.http.routers.portainer.service: "portainer"
          traefik.http.routers.portainer.rule: "Host(`portainer.{{ local_domain }}`)"
          traefik.http.routers.portainer.middlewares: "ip-whitelist@file"
          traefik.http.routers.portainer.entrypoints: "web"
          traefik.http.services.portainer.loadbalancer.server.port: "9000"
        published_ports:
          - "{{ networking.portainer.port }}:9000"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/home/{{ ansible_user }}/portainer/:/data"
        networks:
          - name: networking
            aliases:
              - portainer
        log_driver: json-file
        log_options:
          max-size: "10m"
          max-file: "5"
    - name: Check Portainer container health
      uri:
        url: http://localhost:{{ networking.portainer.port }}
      register: result
      until: result.status == 200
      retries: 10
      delay: 10
