- name: Install Samba
  hosts: networking
  become: yes
  serial: 1
  tasks:
    # ####################################
    # Prepare files
    # ####################################
    - name: Create Samba Media directory
      file:
        path: "{{ networking.samba.media_path }}"
        state: directory
        mode: 0777

    # ####################################
    # Run container
    # ####################################
    - name: Start/Update Samba container
      when: networking.samba.enabled == true
      docker_container:
        name: samba
        image: ghcr.io/servercontainers/samba
        pull: yes
        restart_policy: unless-stopped
        network_mode: host
        privileged: true
        env:
          TZ: "{{ timezone }}"
          MODEL: "TimeCapsule"
          AVAHI_NAME: "StorageServer"
          SAMBA_CONF_LOG_LEVEL: "3"
          GROUP_family: "1500"

          ACCOUNT_homelab: "homelabpass"
          UID_homelab: "1001"
          GROUPS_alice: "family"

          SAMBA_VOLUME_CONFIG_media: "[Media]; path=/shares/media; force user = root; guest ok = yes; writeable = yes; browseable = yes; public = yes"
          SAMBA_VOLUME_CONFIG_downloads: "[Downloads]; path=/shares/downloads; force user = root; guest ok = yes; writeable = yes; browseable = yes; public = yes"
          SAMBA_VOLUME_CONFIG_photography: "[Photography]; path=/shares/photography; force user = root; guest ok = yes; writeable = yes; browseable = yes; public = yes"
        volumes:
          - "/etc/avahi/services/:/external/avahi"

          # avoid loops when mounting folders to /shares (I'd recommend explicit mapping for each share)
          - "{{ networking.samba.media_path }}:/shares/media"
          - "{{ networking.samba.downloads_path }}:/shares/downloads"
          - "{{ networking.samba.photography_path }}:/shares/photography"
        log_driver: json-file
        log_options:
          max-size: "10m"
          max-file: "5"
