- name: Create pihole directory
  file:
    path: "/home/{{ ansible_user }}/pihole"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: 0755

- name: Get IPv6 link local address
  set_fact:
    ipv6: "{{ item.address }}"
  loop: "{{ vars['ansible_' + ansible_default_ipv6.interface | default(ansible_default_ipv4.interface)].ipv6 }}"
  loop_control:
    label: "{{ item.address }}"
  when: "'link' in item.scope"

- name: Set FTLCONF_REPLY_ADDR (HA mode)
  set_fact:
    ftlconf_reply_addr4: "{{ server_cidr.split('/')[0] }}"
    ftlconf_reply_addr6: "{{ pihole_vip_ipv6.split('/')[0] }}"
    execution_mode: "HA setup with keepalived"
  when: pihole_ha_mode

- name: Set FTLCONF_REPLY_ADDR (single mode)
  set_fact:
    ftlconf_reply_addr4: "{{ ansible_host }}"
    ftlconf_reply_addr6: "{{ ipv6 }}"
    execution_mode: "single node setup"
  when: not pihole_ha_mode

- name: Start/Update pihole container
  docker_container:
    name: pihole
    image: "{{ pihole_image }}"
    pull: yes
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.pihole.service: "pihole"
      traefik.http.routers.pihole.rule: "Host(`pihole.{{ local_domain }}`)"
      traefik.http.routers.pihole.middlewares: "ip-whitelist@file"
      traefik.http.services.pihole.loadbalancer.server.port: "{{ pihole_port }}"
    env:
      TZ: "{{ timezone }}"
      FTLCONF_REPLY_ADDR4: "{{ ftlconf_reply_addr4 }}"
      FTLCONF_REPLY_ADDR6: "{{ ftlconf_reply_addr6 }}"
      WEBPASSWORD: "{{ pihole_webpassword }}"
      PIHOLE_DNS_: "{{ pihole_dns }}"
      DNSMASQ_LISTENING: "local"
      WEB_PORT: "{{ pihole_port }}"
      REV_SERVER: "{{ pihole_rev_server }}"
      REV_SERVER_DOMAIN: "{{ local_domain }}"
      REV_SERVER_TARGET: "{{ server_routers_ip }}"
      REV_SERVER_CIDR: "{{ server_cidr }}"
      FTLCONF_MAXDBDAYS: "{{ pihole_ftl_max_db_days }}"
      WEBTHEME: "default-dark"
      VIRTUAL_HOST: "pihole.lc"
    dns_servers:
      - 127.0.0.1
      - "{{ static_dns }}"
    network_mode: host
    volumes:
      - "/home/{{ ansible_user }}/pihole/pihole/:/etc/pihole/"
      - "/home/{{ ansible_user }}/pihole/dnsmasq.d/:/etc/dnsmasq.d/"
    log_driver: json-file
    log_options:
      max-size: "10m"
      max-file: "5"

- name: Check pihole container
  uri:
    url: http://localhost:{{ pihole_port }}/http://192.168.1.33:8200/admin/login.php
  register: result
  until: result.status == 200
  retries: 5
  delay: 10

- name: INFORMATION
  debug:
    msg:
      - "In the {{ execution_mode }} make sure to point your DNS server settings here:"
      - "DNSv4: {{ ftlconf_reply_addr4 }}"
      - "DNSv6: {{ ftlconf_reply_addr6 }}"
