- name: Install Home Assistant
  hosts: other
  become: yes
  serial: 1
  tasks:
    # ####################################
    # Run container
    # ####################################
    - name: Start/Update container
      docker_container:
        name: homeassistant
        image: ghcr.io/home-assistant/home-assistant:stable
        pull: yes
        restart_policy: unless-stopped
        privileged: true
        labels:
          traefik.enable: true
          traefik.http.routers.homeassistant.service: "homeassistant"
          traefik.http.routers.homeassistant.rule: "Host(`homeassistant.{{ local_domain }}`)"
          traefik.http.routers.homeassistant.middlewares: "ip-whitelist@file"
          traefik.http.routers.homeassistant.entrypoints: "web"
          traefik.http.services.homeassistant.loadbalancer.server.port: "8123"

          # TLS
          traefik.http.routers.homeassistant-http.service: "homeassistant"
          traefik.http.routers.homeassistant-http.rule: "Host(`homeassistant.{{ public_wildcard }}`)"
          traefik.http.routers.homeassistant-http.middlewares: "redirect-to-https@file"
          traefik.http.routers.homeassistant-http.entrypoints: "web"

          traefik.http.routers.homeassistant-secure.service: "homeassistant"
          traefik.http.routers.homeassistant-secure.rule: "Host(`homeassistant.{{ public_wildcard }}`)"
          traefik.http.routers.homeassistant-secure.tls: "true"
          traefik.http.routers.homeassistant-secure.tls.certresolver: "master"
          traefik.http.routers.homeassistant-secure.entrypoints: "websecure"

        etc_hosts:
          host.docker.internal: "172.17.0.1"
        env:
          TZ: "{{ timezone }}"
        dns_servers:
          - "127.0.0.1"
          - "{{ static_dns }}"
        network_mode: host
        volumes:
          - "/home/{{ ansible_user }}/homeassistant/:/config"
        log_driver: json-file
        log_options:
          max-size: 10m
          max-file: 5
    - name: Check container health
      uri:
        url: http://localhost:{{ home_assistant_port }}
      register: result
      until: result.status == 200
      retries: 5
      delay: 10
