- name: Install Flaresolverr
  hosts: mediarr
  become: yes
  serial: 1
  tasks:
    - import_tasks: mediarr-setup.yaml

    # ####################################
    # Prepare files
    # ####################################
    - name: Create Flaresolverr config directory
      file:
        path:  /home/{{ ansible_user }}/docker_configs/flaresolverr
        state: directory

    # ####################################
    # Run container
    # ####################################
    - name: Start/Update Flaresolverr container
      when: mediarr.flaresolverr.enabled == true
      docker_container:
        name: flaresolverr
        image: flaresolverr/flaresolverr:v3.3.21
        pull: yes
        restart_policy: unless-stopped
        env:
          TZ: "{{ timezone }}"
          LOG_LEVEL: "info"
        labels:
          traefik.http.routers.flaresolverr.service: "flaresolverr"
          traefik.http.routers.flaresolverr.rule: "Host(`flaresolverr.{{ local_domain }}`)"
          traefik.http.routers.flaresolverr.middlewares: "ip-whitelist@file"
          traefik.http.routers.flaresolverr.entrypoints: "web"
          traefik.http.services.flaresolverr.loadbalancer.server.port: "8191"
        published_ports:
          - "{{ mediarr.flaresolverr.port }}:8191"
        networks:
          - name: mediarr
            aliases:
              - flaresolverr
        log_driver: json-file
        log_options:
          max-size: "10m"
          max-file: "5"
    - name: Check container health
      uri:
        url: http://localhost:{{ mediarr.flaresolverr.port }}
      register: result
      until: result.status == 200
      retries: 10
      delay: 10

    # ####################################
    # Prune
    # ####################################
    - name: Remove old image versions
      docker_prune:
        images: yes
        images_filters:
          dangling: false
