- name: Install Prowlarr
  hosts: mediarr
  become: yes
  serial: 1
  tasks:
    - import_tasks: mediarr-setup.yaml

    # ####################################
    # Prepare files
    # ####################################
    - name: Create Prowlarr config directory
      file:
        path:  /home/{{ ansible_user }}/docker_configs/prowlarr
        state: directory

    # ####################################
    # Run container
    # ####################################
    - name: Start/Update Prowlarr container
      when: mediarr.prowlarr.enabled == true
      docker_container:
        name: prowlarr
        image: lscr.io/linuxserver/prowlarr:arm32v7-develop-version-1.5.2.3484
        pull: yes
        restart_policy: unless-stopped
        env:
          TZ: "{{ timezone }}"
          PUID: "{{ user.user_id }}"
          PGID: "{{ user.group_id }}"
        labels:
          traefik.http.routers.prowlarr.service: "prowlarr"
          traefik.http.routers.prowlarr.rule: "Host(`prowlarr.{{ local_domain }}`)"
          traefik.http.routers.prowlarr.middlewares: "ip-whitelist@file"
          traefik.http.routers.prowlarr.entrypoints: "web"
          traefik.http.services.prowlarr.loadbalancer.server.port: "9696"
        published_ports:
          - "{{ mediarr.prowlarr.port }}:9696"
        volumes:
          - "/home/{{ ansible_user }}/docker_configs/prowlarr:/config"
        networks:
          - name: mediarr
            aliases:
              - prowlarr
        log_driver: json-file
        log_options:
          max-size: "10m"
          max-file: "5"
    - name: Check container health
      uri:
        url: http://localhost:{{ mediarr.prowlarr.port }}
      register: result
      until: result.status == 200
      retries: 10
      delay: 10

    # ####################################
    # Prune
    # ####################################
    - name: Remove old image versions
      docker_prune:
        images: yes
        images_filters:
          dangling: false
