
# ####################################
# Swap for faster updates
# ####################################
- import_playbook: ansible-pihole/bootstrap-pihole.yaml
# - import_playbook: ansible-pihole/update-pihole.yaml


- import_playbook: gramaddict.yaml
- import_playbook: heimdall-docker.yaml
- import_playbook: home-assistant-docker.yaml
- import_playbook: pi-swap-settings.yaml
- import_playbook: portainer-docker.yaml
- import_playbook: rpi-monitor-docker.yaml
- import_playbook: shlink-docker.yaml
- import_playbook: speedtest-tracker-docker.yaml
- import_playbook: traefik-docker.yaml
- import_playbook: wireguard-docker.yaml
- import_playbook: scrumpoker-docker.yaml
