- name: Install Heimdall Dashboard
  hosts: all
  become: yes
  serial: 1
  tasks:
    # ####################################
    # Run container
    # ####################################
    - name: Start/Update container
      docker_container:
        name: heimdall
        image: "lscr.io/linuxserver/heimdall:latest"
        pull: yes
        restart_policy: unless-stopped
        labels:
          traefik.http.routers.heimdall.service: "heimdall"
          traefik.http.routers.heimdall.rule: "Host(`heimdall.{{ local_domain }}`)"
          traefik.http.routers.heimdall.middlewares: "ip-whitelist@file"
          traefik.http.routers.heimdall.entrypoints: "web"
          traefik.http.services.heimdall.loadbalancer.server.port: "80"

          traefik.http.routers.dashboard.service: "heimdall"
          traefik.http.routers.dashboard.rule: "Host(`dashboard.{{ local_domain }}`)"
          traefik.http.routers.dashboard.middlewares: "ip-whitelist@file"
          traefik.http.routers.dashboard.entrypoints: "web"
        env:
          TZ: "{{ timezone }}"
          PUID: "1000"
          PGID: "1000"
        published_ports:
          - "{{ heimdall_port }}:80"
        volumes:
          - "/home/{{ ansible_user }}/heimdall/:/config"
        log_driver: json-file
        log_options:
          max-size: "10m"
          max-file: "5"
    - name: Check container health
      uri:
        url: http://localhost:{{ heimdall_port }}
      register: result
      until: result.status == 200
      retries: 5
      delay: 10

    # ####################################
    # Clear
    # ####################################
    - name: Remove old image versions
      docker_prune:
        images: yes
        images_filters:
          dangling: false
