- import_playbook: networking/portainer.yaml
  when: networking.portainer.enabled == true
- import_playbook: networking/traefik.yaml
  when: networking.traefik.enabled == true
- import_playbook: networking/samba.yaml
  when: networking.samba.enabled == true
- import_playbook: networking/wireguard.yaml
  when: networking.wireguard.enabled == true
- import_playbook: networking/speedtest-tracker.yaml
  when: networking.speedtest-tracker.enabled == true
