- name: Install RPi Monitor
  hosts: all
  become: yes
  serial: 1
  tasks:
    # ####################################
    # Run container
    # ####################################
    - name: Start/Update container
      docker_container:
        name: rpi-monitor
        image: "michaelmiklis/rpi-monitor:latest"
        pull: yes
        restart_policy: unless-stopped
        env:
          TZ: "{{ timezone }}"
        labels:
          traefik.http.routers.rpimonitor.service: "rpimonitor"
          traefik.http.routers.rpimonitor.rule: "Host(`rpimonitor.{{ local_domain }}`)"
          traefik.http.routers.rpimonitor.middlewares: "ip-whitelist@file"
          traefik.http.routers.rpimonitor.entrypoints: "web"
          traefik.http.services.rpimonitor.loadbalancer.server.port: "8888"
        published_ports:
          - "{{ rpi_monitor_port }}:8888"
        devices:
          - /dev/vchiq
          - /dev/vcsm-cma
        volumes:
          - /opt/vc:/opt/vc
          - /boot:/boot
          - /sys:/dockerhost/sys:ro
          - /etc:/dockerhost/etc:ro
          - /proc:/dockerhost/proc:ro
          - /usr/lib:/dockerhost/usr/lib:ro
        log_driver: json-file
        log_options:
          max-size: "10m"
          max-file: "5"
    - name: Check container health
      uri:
        url: http://localhost:{{ rpi_monitor_port }}
      register: result
      until: result.status == 200
      retries: 5
      delay: 10

    # ####################################
    # Clear
    # ####################################
    - name: Remove old image versions
      docker_prune:
        images: yes
        images_filters:
          dangling: false
